In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#training df
path = "./data/fin_df_103019.csv"
df = pd.read_csv(path)
df.head()

,text,hashtags,user_name,date,user_location,label
0,Congrats pre,NaN,MasterAR9012502,2019-10-24 15:05:01+00:00,NaN,0
1,Wassup?,NaN,theprejon,2019-10-21 20:54:33+00:00,NaN,0
2,"Ini mbc korea yang komen orang indo semueh,, b...",NaN,KhoyrR,2019-10-24 14:19:01+00:00,NaN,0
3,Meron pre?,NaN,Zendriccccc,2019-10-26 13:00:29+00:00,NaN,0
4,this is their pre-p3p5 fam love story thanks,NaN,akihikologist,2019-10-21 02:44:47+00:00,NaN,0

In [3]:
def clean_time(df, column="date"):
    #drop rows with no date information 
    df = df.dropna(subset=["date"])
    #split day and time information
    df["split_date"] = df["date"].str.split("-")
    #pull out month and make column
    df["month"] = df["split_date"].str.get(1).astype(int)
    #pull out day/time information
    df["time"] = df["split_date"].str.get(2)
    #split day from time on space
    df["time_split"] = df["time"].str.split(" ")
    #pull out day
    df["day"] = df["time_split"].str.get(0).astype(int)
    #now look at time
    df["time_col"] = df["time_split"].str.get(1)
    #split on + to separate out time from timezone
    df["hour_min_sec"] = df["time_col"].str.split("+")
    #all timezones are assumed to be GMT so ignoring and focusing on time
    df["hour_min_sec"] = df["hour_min_sec"].str.get(0)
    df["hour_min_sec_split"] = df["hour_min_sec"].str.split(":")
    df["hour"] = df["hour_min_sec_split"].str.get(0).astype(int)
    df["minute"] = df["hour_min_sec_split"].str.get(1).astype(int)
    df["second"] = df["hour_min_sec_split"].str.get(2).astype(int)
    #dropping temp columns I made
    df = df.drop(columns=["date", "split_date", "time", "time_split", "time_col", "hour_min_sec", "hour_min_sec_split"])
    return df

In [4]:
clean_time(df)

/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/dsi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,text,hashtags,user_name,user_location,label,month,day,hour,minute,second
0,Congrats pre,NaN,MasterAR9012502,NaN,0,10,24,15,5,1
1,Wassup?,NaN,theprejon,NaN,0,10,21,20,54,33
2,"Ini mbc korea yang komen orang indo semueh,, b...",NaN,KhoyrR,NaN,0,10,24,14,19,1
3,Meron pre?,NaN,Zendriccccc,NaN,0,10,26,13,0,29
4,this is their pre-p3p5 fam love story thanks,NaN,akihikologist,NaN,0,10,21,2,44,47
...,...,...,...,...,...,...,...,...,...,...
2723,What does North of Soledad Cyn Rd mean? Maybe ...,#TICKFIRE #lacofdpio,NormadyThomas,NaN,1,10,25,4,2,37
2724,Closing freeway to traffic coming north in cer...,#KincadeFire #evacuate,clairefelicite2,NaN,1,10,26,23,20,44
2725,Nuove evacuazioni I saw this on the BBC and th...,#Californiawildfires,paoloigna1,NaN,0,10,26,22,20,48
2726,Stay safe everyone and be careful goodnight #T...,#TickFire,jessica2sweet,NaN,0,10,25,5,53,44
2727,Our thoughts are with everyone affected by the...,#kincadefire,trialtowines,NaN,0,10,25,21,25,34